### ISSUE TITLE
Silently failing

### ISSUE THREAD

**Issue by mancvso** [dozd/mongo-mapper#1]
When the mapping cannot be achieved, it does not throw ant exception neither message.

In my case, having an entity saved in mongo `{ name: String }` but having declared

``` java
class Something {
  public String name;
  public Object notexistantindb;
}
```

Will fail silently and I find it concerning when evolving the Scheme.

PD: ¿Can you point me to some other libs that use the async driver?

**Comment by mancvso** [comment]
Just wanted to add that the correct data in mongo should be

``` json
{
  "name": "some string",
  "notexistantindb": null
}
```

**Comment by dozd** [comment]
I don't get it - what's desired behavior? If you have only `{ name: String}` in the db, your object will have field `notexistantindb` set to `null` and it's working in that way.

**Comment by dozd** [comment]
No more info. Closing.
