### ISSUE TITLE
Embedded Classes

### ISSUE THREAD

**Issue by mancvso** [dozd/mongo-mapper#2]
There are certain classes that do not need an ID attribute. I suggest using the `@Embedded` annotation for classes that do not live outside other documents. Like in Morphia.

**Comment by dozd** [comment]
How are `@Embedded` objectes stored in mongo DB? Are they in the same collection as parrent object who has Embedded dependency or in separate collection? Could you provide example? Thanks.

**Comment by mancvso** [comment]
They are stored in the parent object.

For example, two dependent classes

``` java
@Entity
class Parent {
  @Id String id;
  String name;
  Child child;
}

@Embedded
class Child {
  String description;
}
```

They are translated in MongoDB to

``` json
{
  "_id": ObjectId("muchhexadecimalid"),
  "name": "Much name",
  "child" : {
    "description" : "Much description"
   }
}
```

A real example with Morphia is

``` json
{
    "_id" : ObjectId("56aa7bdbd4f46c101e483451"),
    "className" : "models.entidades.Usuario",
    "nombre" : "juanito",
    "plan" : {
        "inicio" : {
            "year" : 2016,
            "month" : 1,
            "day" : 28
        },
        "plan" : "Gratuito"
    }
}
```

Where "plan" is an embedded class.

**Comment by dozd** [comment]
Yeah, it won't be hard to implement this. I'll take a look at it during weekend.
